example-project/harveproject/harveproject/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('livro.urls'))
]

example-project/harveproject/livro/urls.py
from django.urls import path

from . import views

app_name = 'livro'
urlpatterns = [
    path('', views.ola_mundo, name='ola_mundo'),
    path('livros/', views.exibe_livros, name='exibe_livros'),
    path('livros/<int:indice_livro>/', views.detalhe_livro, name='detalhe_livro'),
    path('livros/cadastro', views.novo_livro, name='cadastro_livro')
]

example-project/harveproject/livro/models.py
from django.db import models


class Livro(models.Model):
    nome = models.CharField(max_length=200)
    nome_autor = models.CharField(max_length=200)
    paginas = models.IntegerField()

example-project/harveproject/livro/forms.py
from django import forms

from .models import Livro


class LivroForm(forms.ModelForm):
    class Meta:
        model = Livro
        fields = ['nome', 'nome_autor', 'paginas']

example-project/harveproject/livro/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404

from .models import Livro
from .forms import LivroForm


# retorna o template que devolve "Ola mundo!"
def ola_mundo(request):
    # chamamos o template ola_mundo.html
    return render(request, 'ola_mundo.html')


# view responsavel por carregar todos os livros e repassar para o template
def exibe_livros(request):
    livros = Livro.objects.all()
    context = {'lista_livros': livros}
    return render(request, 'exibe_livros.html', context=context)


# view responsavel por carregar um livro dado o indice
def detalhe_livro(request, indice_livro):
    livro = get_object_or_404(Livro, pk=indice_livro)
    context = {'livro': livro}
    return render(request, 'detalhe_livro.html', context)


# view responsavel por guardar um novo livro
def novo_livro(request):
    if request.method == 'POST':
        form = LivroForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'sucesso.html')
    else:
        form = LivroForm()
    return render(request, 'novo_livro.html', {'form': form})

example-project/harveproject/livro/templates/detalhe_livro.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/livro.css' %}">
    </head>
    <body>
        <p> Nome do livro: {{livro.nome}} <p>
        <p> Nome do autor: {{livro.nome_autor}} <p>
        <p> Número de páginas {{livro.paginas}} <p>
    </body>
</html>

example-project/harveproject/livro/templates/exibe_livros.html
<p>Lista de livros</p>
<p>{{lista_livros}}</p>

<ul>
    {% for livro in lista_livros %}
        <li>{{livro}}</li>
    {% endfor %}
</ul>

<ul>
    {% for livro in lista_livros %}
        <li>{{livro.nome}} {{livro.nome_autor}} {{livro.paginas}}</li>
    {% endfor %}
</ul>

<ul>
    {% for livro in lista_livros %}
        <li>
            <a href="{% url 'livro:detalhe_livro' livro.id %}">{{ livro.nome}}</a>
        </li>
    {% endfor %}
</ul>

example-project/harveproject/livro/templates/novo_livro.html
<form action="cadastro" method="post">
    <p> Cadastro de novo livro </p>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

example-project/harveproject/livro/templates/ola_mundo.html
<h1>Olá mundo!</h1>

<li> Exemplo lista:
    <ul>Item 1</ul>
    <ul>Item 2</ul>
    <ul>Item 3</ul>
</li>

example-project/harveproject/livro/templates/sucesso.html
<h1>Sucesso!!!!!</h1>